# -*- coding: utf-8 -*-
"""IP31-Inceptionv3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qxaAx5Hx8nVo4r0NWhOjeV547YUjJS-4

###Data
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import shutil
import random
import itertools
import numpy as np
import pandas as pd
import keras.metrics
from PIL import Image
from skimage import io
import tensorflow as tf
from tensorflow.keras import Model
from tensorflow import keras
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from tensorflow.keras.optimizers import Adam, RMSprop
from tensorflow.keras.models import Sequential
from tensorflow.keras.metrics import categorical_crossentropy
from tensorflow.keras.layers import Activation, Dense, Flatten, Conv2D, MaxPool2D, Dropout, BatchNormalization, GlobalAveragePooling2D, Concatenate
from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras.preprocessing.image import ImageDataGenerator, img_to_array, array_to_img
# %matplotlib inline

!gdown --id "1-txGiJZhCBQJs6a7XtEc7_7CmpbN86Tz"
!unzip *zip

def plot_cm(cm, classes, normalize = False , title = 'Confusion Matrix', cmap = plt.cm.Blues):
  plt.imshow(cm, interpolation = 'nearest', cmap = cmap)
  plt.title(title)
  plt.colorbar()
  tick_marks = np.arange (len(classes))
  plt.xticks(tick_marks, classes, rotation = 45)
  plt.yticks(tick_marks, classes)

  if normalize:
    cm = cm.astype('float')/cm.sum(axis =1)[:,np.newaxis]
    print("Normalized CM")
  else:
    print ('Confusion Matrix, without normalization')
  print(cm)

  thresh  = cm.max()/2
  for i,j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
    plt.text(j,i,cm[i,j],horizontalalignment = 'center', color = 'white' if cm[i,j]>thresh else"black")

  plt.tight_layout()
  plt.ylabel('True Label')
  plt.xlabel('Predicted Label')

data300 = 'casting_data/casting_data'
train_dir = data300+'/train'
test_dir = data300+'/test'
val_dir = data300 + '/validation'

val_ok = data300 + '/validation/ok_front'
val_def = data300 + '/validation/def_front'

train_def_300 = data300+'/train/def_front'
train_ok_300 = data300+'/train/ok_front'

test_def_300 = data300+'/test/def_front'
test_ok_300 = data300+'/test/ok_front'

print(' No. of images in train_def_300 : ', len(os.listdir(train_def_300)))
print(' No. of images in train_ok_300 :  ' , len(os.listdir(train_ok_300)))

print(' No. of images in test_def_300 :  ', len(os.listdir(test_def_300)))
print(' No. of images in test_ok_300 :   ', len(os.listdir(test_ok_300)))

temp1 = 0
temp2 = 0
os.makedirs(val_def)
os.makedirs(val_ok)

#moving 654 images to val_ok

if temp1 ==0:
  for i in range(654):
    img_name = random.choice(os.listdir(train_ok_300))
    img_path = train_ok_300+'/'+img_name 
    shutil.move(img_path, val_ok+'/'+img_name)
    temp1 +=1
else:
  print('already performed this operation')

#moving 1090 images to val_def

if temp2 ==0:
  for i in range(1090):
    img_name = random.choice(os.listdir(train_def_300))
    img_path = train_def_300+'/'+img_name 
    shutil.move(img_path, val_def+'/'+img_name)
    temp1 +=1
else:
  print('already performed this operation')

assert len(os.listdir(val_def)) == 1090
assert len(os.listdir(val_ok)) == 654

train_batches = ImageDataGenerator(preprocessing_function= tf.keras.applications.vgg16.preprocess_input).flow_from_directory(directory = train_dir,
                                                                                target_size = (224,224), classes = ['def_front','ok_front'], batch_size =32)

validation_batches = ImageDataGenerator(preprocessing_function= tf.keras.applications.vgg16.preprocess_input).flow_from_directory(directory = val_dir,
                                                                                target_size = (224,224), classes = ['def_front','ok_front'], batch_size =32)

test_batches = ImageDataGenerator(preprocessing_function= tf.keras.applications.vgg16.preprocess_input).flow_from_directory(directory = test_dir,
                                                                                target_size = (224,224), classes = ['def_front','ok_front'], batch_size =32, shuffle = False)

"""### Model"""

base_model = tf.keras.applications.InceptionV3(weights='imagenet', 
                                include_top=False, 
                                input_shape=(224, 224,3))

base_model.trainable = False

last_layer = base_model.get_layer('mixed7')
last_output = last_layer.output

x = Flatten()(last_output)
x = Dense(1024, activation='relu')(x)
x = Dropout(0.2)(x)
x = Dense(2, activation='softmax')(x)

model = Model(base_model.input, x)

model.compile(optimizer=RMSprop(lr=0.0001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if(logs.get('accuracy') > 0.99 and logs.get('val_accuracy') > 0.99):
            print("\nCancelling training as model has reached 99% accuracy and 99% validation accuracy!")
            self.model.stop_training = True

callbacks = myCallback()
history = model.fit_generator(train_batches,validation_data=validation_batches,epochs=50,verbose=1,
                              callbacks=[callbacks])

pd.DataFrame(history.history).plot(figsize=(10,6))
plt.show()

prediction = model.predict(x=test_batches, verbose=1)

cm = confusion_matrix(y_true=test_batches.classes, y_pred = np.argmax(prediction, axis=-1))

cm_plotlabels = ['defective','ok']
plot_cm(cm, classes = cm_plotlabels )







model = Sequential()

model.add(base_model)

model.add(GlobalAveragePooling2D())
model.add(Dropout(0.25))
model.add(Dense(2, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer= Adam(lr=0.0001), metrics=['accuracy'])

model.summary()

history = model.fit(train_batches, validation_data=validation_batches, verbose =1, epochs = 25)

pd.DataFrame(history.history).plot(figsize=(10,6))
plt.show()



"""###Prediction"""

prediction = model.predict(x=test_batches, verbose=1)

# test_batches.classes

cm = confusion_matrix(y_true=test_batches.classes, y_pred = np.argmax(prediction, axis=-1))

# cm_plotlabels = ['defective','ok']
# plot_cm(cm, classes = cm_plotlabels )    //////VGG_16

cm_plotlabels = ['defective','ok']
plot_cm(cm, classes = cm_plotlabels )

